LiftType.create!(id: -1, name: 'inne')
LiftType.create!(name: 'spożywka', condition: "name like '%KAUFLAND%' or name like '%LIDL%' or name like '%BIEDRONKA%' or name like '%DELIKATESY%' or name like '%POLSKA SIEC HANDLOWA NASZ%'")
LiftType.create!(name: 'remont', condition: "name like '%MERKURY MARKET%' or name like '%MAJSTER%' or name like '%MROWKA%'")
LiftType.create!(name: 'kosmetyka', condition: "name like '%ROSSMANN%'")
LiftType.create!(name: 'paliwo', condition: "name like '%LOTOS%' or name like '%FH TANK%' or name like '%DAREX%' or name like '%RiA%' or name like '%ORLEN%'")
LiftType.create!(name: 'samochód', condition: "name like '%AUTO-RES%'")
LiftType.create!(name: 'ubezpieczenie', condition: "name like '%HERSTIA%'")
LiftType.create!(name: 'zdrowie', condition: "name like '%APTEKA%' or name like '%CEFARM%'")
LiftType.create!(name: 'mieszkanie', condition: "name like '%SPÓŁDZIELNIA MIESZKANIOWA%'")
LiftType.create!(name: 'rtv/agd', condition: "name like '%EURO-NET%'")
